<?php

namespace ProblemeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FruitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FruitsRepository extends EntityRepository
{
}
