ProblemeBundle\Entity\Client:
    type: entity
    table: null
    repositoryClass: ProblemeBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        client:
            type: string
            length: 255
        consomation_de_banane:
            type: integer
        consomation_de_pomme:
            type: integer
        consomation_ananas:
            type: integer
    lifecycleCallbacks: {  }


    manytoMany:
       fruits:
          targetentity: Problemebundle\Entity\Client
          mappedBy: clients
